---
- hosts: all
  become: yes
  gather_facts: no

  vars:
    binary: false

  tasks:
  - name: Install packages for headless host
    yum:
      name: "{{ item }}"
      state: latest
    loop:
    - qemu-kvm
    - libvirt
    - libvirt-python
    - libguestfs-tools
    - virt-install
    - https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_x86_64.rpm
    - libvirt-devel
    - ruby-devel
    - gcc

  - name: Enable and start Libvirtd
    systemd:
      state: started
      name: libvirtd
      enabled: yes

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      groups: "{{ item }}"
      append: yes
    loop:
    - qemu
    - libvirt

  - name: Pull a minimal install iso
    get_url:
      url: http://mirror.cs.pitt.edu/centos/7.5.1804/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso
      dest: /var/lib/libvirt/boot/CentOS-7-x86_64-Minimal-1804.iso
      mode: 0644
      owner: root
      group: root
    when: binary
  
  - name: Install libvirt plugin for Vagrant
    command: "vagrant plugin install vagrant-libvirt"
    become: yes
    become_user: vagrant

  - name: Add test libvirt box
    command: "vagrant box add eightbitdino/homelab --provider libvirt"
    become: yes
    become_user: vagrant
    when: binary

  - name: Add Vagrantfile for test box
    copy:
      src: Vagrantfile_internal
      dest: /home/vagrant/Vagrantfile
      owner: vagrant
      group: vagrant
      mode: 0644
    when: binary