---
- hosts: all
  become: yes

  tasks:
  - name: Copy ZeroTier install script to box
    copy:
      src: zerotier_install.sh
      dest: /tmp/zerotier_install.sh
      owner: root
      group: root
      mode: 0755
      
  - name: Install Zerotier
    command: "/tmp/zerotier_install.sh"

  - name: Remove ZeroTier install script
    file:
      path: "/tmp/zerotier_install.sh"
      state: absent